// This file is generated by Slice Machine. Update with care!

import ButtonBlock from './ButtonBlock';
import Columns from './Columns';
import Endorsement from './Endorsement';
import LargeText from './LargeText';
import LargeTextBlock from './LargeTextBlock';

export {
	ButtonBlock,
	Columns,
	Endorsement,
	LargeText,
	LargeTextBlock,
};

export const components = {
	button_block: ButtonBlock,
	columns: Columns,
	endorsement: Endorsement,
	large_text: LargeText,
	large_text_block: LargeTextBlock,
};
